### ISSUE TITLE
'3dio' is not a valid attribute name

### ISSUE THREAD

**Issue by frederic-schwarz** [archilogic-com/3dio-js#10]
`3dio` is not a valid attribute name for DOM elements because it starts with a number
therefore simple javascript commands like `el.setAttribute('3dio-data3d', val)` fail

jsfiddle to showcase the problem
https://jsfiddle.net/9yu7pdkq/1/

possible solution:
rename
`3dio-data3d` to `io3d-data3d`
&
`3dio-furniture` to `io3d-furniture`

**Comment by tomas-polach** [comment]
io3d would be inline with IO3D - let's roll with it.
TODO:
- [ ] update library
- [ ] update https://jsfiddle.net/3dio/5wgoq2u7/
- [ ] update https://glitch.com/edit/#!/3dio-aframe
- [ ] update io3d-js README.md
- [ ] update examples inside io3d-js repo
