### ISSUE TITLE
utils/processing methods cannot be called from node.js because of window reference 

### ISSUE THREAD

**Issue by bnjm** [archilogic-com/3dio-js#101]
**To reproduce** 

call `io3d.utils.processing.whenDone` from any node.js runtime

**Actual result**

Thrown error:  `window is not defined`

**Expected**

Either method to work, or error message like `"method not supported from non-browser environments"`

**Comment by Aadjou** [comment]
An error message should only be a temporary solution

**Comment by bnjm** [comment]
Sorry I did not mean to push to master, but easy fix in https://github.com/archilogic-com/3dio-js/commit/fcf59557f665575dded521d64cd366a50505ea9b

**Comment by bnjm** [comment]
Since I pushed to master without the chance for a review, I will just explain that the problem was caused by using `window.setTimeout` instead of `setTimeout`. 

Probably window.setTimeout is nicer to use since it avoids introducing a new global reference, but it throws an error in node.js... also global setTimeout is referenced a few times elsewhere like https://github.com/archilogic-com/3dio-js/blob/master/src/utils/wait.js
