### ISSUE TITLE
Importing an Archilogic scene with non standard coordinate system into 3d.io fails

### ISSUE THREAD

**Issue by david-tran-archilogic** [archilogic-com/3dio-js#105]
**How to reproduce:**
- import obj file with flipped Y/Z coordinate system into the editor
- click on the "flip y/z" checkbox
- (select correct units from dropdown menu)
- save model
- open 3d.io appcreator
- paste archilogic link into appreactor

**Expected behaviour:**
- imported obj file has the correct scale and rotation in A-Frame scene

**Actual result:**
- imported obj file has the wrong rotation and scale in A-Frame scene

**Test with this Archilogic scene:**
https://spaces.archilogic.com/model/archilogic/rfs47xeh?modelResourceId=7730663c-59dc-4dab-b6b8-616c9907ba34&mode=edit&view-menu=none&main-menu=interior&logo=false

**Comment by frederic-schwarz** [comment]
will be solved with architectural toolkit release
( overall improved a-frame import )

**Comment by frederic-schwarz** [comment]
related #103

**Comment by frederic-schwarz** [comment]
scale is alread taken care of
TODO: support `flipYZ: true` parameter
