### ISSUE TITLE
bakedModel is invisible in A-Frame if scene is saved before preview bake is done

### ISSUE THREAD

**Issue by frederic-schwarz** [archilogic-com/3dio-js#109]
reproduce:
- open unbaked model in editor
- bake preview
- save before bake is finished
- import via scene.getAframeElements()

result:
- result baked model is not showing up because there is no bakedModelUrl yet

**Comment by frederic-schwarz** [comment]
reported by Tino from Archilyse

**Comment by AVGP** [comment]
thx for the fix! Someone else just reported it as well 😱
