### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'mesh_0' of undefined

### ISSUE THREAD

**Issue by frederic-schwarz** [archilogic-com/3dio-js#11]
io3d-furniture component produces error when data3d does not have `alternativeMaterialsByMeshKey` property

**Comment by tomas-polach** [comment]
@frederic-schwarz has this one been fixed in https://github.com/archilogic-com/3dio-js/commit/c57fd81dc1563747c13e80687a886bd52b524331 ? aka can i close this?
