### ISSUE TITLE
Camera Bookmarks on 3d.io broken

### ISSUE THREAD

**Issue by dburgauer** [archilogic-com/3dio-js#115]
Open the default_setup on AppCreator
Click the different camera bookmarks
On each click, the camera jumps back to origin first and then animates to the clicked position (vs. interpolating between current and new)

![gif2](https://user-images.githubusercontent.com/28351558/34156791-136c4ca6-e4bf-11e7-8488-31906c16647e.gif)

**Comment by AVGP** [comment]
On it.

**Comment by tomas-polach** [comment]
just for reference: https://stackoverflow.com/questions/47882683/waypoints-position-and-rotation-are-empty-from-the-scene-api

**Comment by AVGP** [comment]
It can be fixed with one line substitution:

```html
<script src="https://unpkg.com/aframe-animation-component@3.2.5/dist/aframe-animation-component.min.js"></script>
```

So I will:

* update our docs
* update the samples

**Comment by dburgauer** [comment]
Thanks @AVGP for the super fast response!

**Comment by AVGP** [comment]
Fixed the sample apps and the docs.
