### ISSUE TITLE
Issue Cannot read property 'pauseAnimation' of undefined

### ISSUE THREAD

**Issue by axelmarciano** [archilogic-com/3dio-js#119]
Hi when i try to switch between waypoints with tour.goTo() i got an issue : Cannot read property 'pauseAnimation' of undefined.

**Comment by Aadjou** [comment]
could you maybe send us your example code / scene in a glitch file or as an app from the [appcreator](https://appcreator.3d.io/default_setup?m=nv)

Thank you. Also please consider the [contribution guidelines](https://github.com/archilogic-com/3dio-js/blob/master/CONTRIBUTING.md) and update your issue accordingly

**Comment by frederic-schwarz** [comment]
Sounds like you forgot to load the `aframe-animation-component`
make sure to use version 3.2.5 like in the example
https://3d.io/docs/api/1/aframe-components.html#tour

**Comment by axelmarciano** [comment]
Indeed, i forgot to load the animation-component. Thanks for ur help
