### ISSUE TITLE
Design method to get all models' sceneId of user/org

### ISSUE THREAD

**Issue by mope1** [archilogic-com/3dio-js#123]
https://3d.io/docs/api/1/scene.html talks about the ``sceneId`` and suggests to copy-paste it out of the URL, but there is no documented way to do this in an automated fashion in the public API.

I suggest we add a well-documented function to get all the sceneId of all models accessible to an API user, and probably also some metadata that belongs to the scenes such as name

**Comment by tomas-polach** [comment]
Yep. We should do this. It should a part of next "Scene API" milestone.
Let's start with designing the exposed API method. Method name ideas: `io3d.scene.list` or `io3d.scene.search`.

**Comment by tomas-polach** [comment]
@mope1 As a workaround you can access the internal server-side endpoints directly. Just be aware that those might change in the future... Here is two possible ways how to do that: (Hope it unblocks you. Let me know)

### Vanilla JS (= plain JS, no libs, no depedencies)
```js
callJsonRpcApi(
  'https://spaces.archilogic.com/api/v2',
  'Model.search',
  {arguments: {folderResourceId: "be81a09f-c6c1-4914-b68a-57185aece1b1"}}
).then(console.log)

function callJsonRpcApi (url, method, params) {
  return fetch(url, {
    method: 'POST',
    body: JSON.stringify({
      method: method,
      params: params,
      jsonrpc: '2.0',
      id: Math.round(Math.random() * 1e20).toString()
    })
  }).then(function(response){
    if (!response.ok) return Promise.reject(response.statusText)
    esle return response.json()
  }).then(function(rpcMessage){
    if (rpcMessage.error) return Promise.reject(rpcMessage.error.message)
    else return rpcMessage.result
  })
}
```

### 3dio.js utils
```js
io3d.utils.services.call(
  'Model.search',
  {arguments: {folderResourceId: "be81a09f-c6c1-4914-b68a-57185aece1b1"}}
).then(console.log)
```

**Comment by tomas-polach** [comment]
@mope1 just updated the vanilla JS example adding `headers:{'content-type': 'application/json'}` as the server requires those to be set. Here is a working jsFiddle: https://jsfiddle.net/xq1qrh9r/
