### ISSUE TITLE
archilogic light setup component

### ISSUE THREAD

**Issue by frederic-schwarz** [archilogic-com/3dio-js#14]
rebuild the light setup from the editor as an aframe component

**Comment by tomas-polach** [comment]
to do:
- design API for lighting component
- decide on name (`lighting` vs. `io3d-lighting`)

for experimenting i created branch `lighting-component` with a new component called `lighting` using code from the editor.

**Comment by frederic-schwarz** [comment]
I changed component to use a-frame lights - so users can edit them in the inspector
also fixes shadows and specular on materials

A-Frame standard

![screenshot 2017-10-01 00 49 14](https://user-images.githubusercontent.com/7444615/31050574-fd5fe0de-a64e-11e7-9aa8-b8eb235d08fe.png)

New default setup:

![screenshot 2017-10-01 00 48 17](https://user-images.githubusercontent.com/7444615/31050576-0557a894-a64f-11e7-9b05-52b0ed978538.png)

morning:

![screenshot 2017-10-01 02 22 41](https://user-images.githubusercontent.com/7444615/31050599-80fbbb8e-a64f-11e7-8072-b5ebaa3da0d0.png)

night:

![screenshot 2017-10-01 02 22 49](https://user-images.githubusercontent.com/7444615/31050600-875b2b04-a64f-11e7-94b4-3a2c4bd55b8a.png)

**Comment by frederic-schwarz** [comment]
proposal for using component on scene element:
```html
<a-scene lighting>
</a-scene>
```
```html
<a-scene io3d-lighting>
</a-scene>
```

**Comment by frederic-schwarz** [comment]
Previous setup was doing no good to interiors -  so new default now tested with basic models and premium models

A-Frame - standard:

![screenshot 2017-10-02 09 21 01](https://user-images.githubusercontent.com/7444615/31067536-b099c30e-a753-11e7-83d8-61946e2d8343.png)

new default:

![screenshot 2017-10-02 09 20 40](https://user-images.githubusercontent.com/7444615/31067622-1dc2ac16-a754-11e7-99e5-782223f35f33.png)

A-Frame - standard:

![screenshot 2017-10-02 09 20 27](https://user-images.githubusercontent.com/7444615/31067627-233f6b84-a754-11e7-8990-60b089bb41dc.png)

new default:

![screenshot 2017-10-02 09 20 11](https://user-images.githubusercontent.com/7444615/31067635-2b8491ac-a754-11e7-9fa2-c77f496d66fb.png)

A-Frame standard:

![screenshot 2017-10-02 09 19 51](https://user-images.githubusercontent.com/7444615/31067645-39c6dc8e-a754-11e7-95be-35cbba7ff3fc.png)

new default:

![screenshot 2017-10-02 09 19 36](https://user-images.githubusercontent.com/7444615/31067684-63692aba-a754-11e7-92a4-aa418f0c4765.png)

**Comment by tomas-polach** [comment]
it's so much nicer now!!

here is some inspirations for future `presets`:

"emotionalized" colors:
![223376481121a835693c919d9a7f4493--environment-concept-environment-design](https://user-images.githubusercontent.com/6619499/31186925-6f9fdad0-a930-11e7-9d6a-9d6b509a7a12.jpg)

morning light:
![static1 squarespace](https://user-images.githubusercontent.com/6619499/31186920-6e52fd38-a930-11e7-9f2e-99f4c2e59365.jpg)
