### ISSUE TITLE
how to refresh tour way-points list

### ISSUE THREAD

**Issue by 1flyby** [archilogic-com/3dio-js#143]
h1 everyone, i'm w8ing your answer on stack so many days! 
https://stackoverflow.com/questions/50880287/camera-tour-points-refresh-in-3d-io
already got achieve:
"Tumbleweed"
Asked a question with zero score, no answers, no comments, and low views for a week
I can't find solution for updating camera's tour way-points after swap or add new way-point.
Sry, i know, this is not a bug, but i d't know, what i can to do... Help me, please.

**Comment by frederic-schwarz** [comment]
thanks for your question, please wait for the answer on SO, this is not a support forum
