### ISSUE TITLE
broken textures with aframe >= 0.8.0 

### ISSUE THREAD

**Issue by BoryaMogila** [archilogic-com/3dio-js#145]
**How to Reproduce**
- [glitch](https://topaz-lute.glitch.me/)

**Actual Result**
- textures not working on furniture
- I think problem with mapDiffuse property in textures
- [screenshot](https://prnt.sc/kcprj4)

**Comment by tomas-polach** [comment]
Will keep this open until next release.

@BoryaMogila Thank you for reporting this bug and providing a test-case. Very helpfull! Here is the fix in action: https://smooth-skirt.glitch.me/
