### ISSUE TITLE
Update 3dio Docs to reflect 1 business day turn around time

### ISSUE THREAD

**Issue by sjeftijssen** [archilogic-com/3dio-js#146]
I am not sure where to put this issue so putting it here:

Current API documentation states:
===
Conversion Request
 io3d.floorPlan.convertToBasic3dModel() allows you to send a request to our conversion API from a custom node server.

The result is not instant but can take up to 12 hours. This is why you need to provide a callback url from your node server to receive the callback when the conversion is finished.

===

We should change it to say that it usually takes up to one business day.

**Comment by tomas-polach** [comment]
Done. Deployment in progress. The updated version should be online in ca. 20min.
