### ISSUE TITLE
Allow upload to specific destination in IO3D.storage.put method

### ISSUE THREAD

**Issue by tomas-polach** [archilogic-com/3dio-js#19]
We want to allow file uploads to specific locations inside user dir.

# proposal [1]
using relative path (shortest code but highest confusion potential)
```javascript
IO3D.storage.put(file, {
	// full path
	key: '/ed245e57-7906-4995-8ac2-e742ce107092/170207-1525-1bqjks/floorplan.jpg',
	// or: (no leading slash = relative to user dir)
	key: '170207-1525-1bqjks/floorplan.jpg'
})
```

# proposal [2]
template syntax (gets replaced inside api method)
```javascript
IO3D.storage.put(file, {
	// full path:
	key: '/ed245e57-7906-4995-8ac2-e742ce107092/170207-1525-1bqjks/floorplan.jpg',
	// or:
	key: '/{{userId}}/170207-1525-1bqjks/floorplan.jpg'
})
```

# proposal [3]
complementary to [1] and [2]
the "proper way" but more code
```javascript
IO3D.auth.getSession().then(function(session){
	// check authentication
	if (!session.isAuthenticated) return alert('Please log in first')
	// upload
	return IO3D.storage.put(file, {
		// full path only:
		key: session.user.id + '/170207-1525-1bqjks/floorplan.jpg'
	})
})
```

**Comment by tomas-polach** [comment]
i suggest to implement [3] and [2] for convenience. @frederic-schwarz @AVGP can you pls have a look if i forgot something?

**Comment by frederic-schwarz** [comment]
ok with [2] and [3]
in 2 would I be able to overwrite your file?
IO3D.storage.put(file, {
	key: '/{{tomas-id}}/170207-1525-1bqjks/floorplan.jpg'
})

**Comment by tomas-polach** [comment]
no. the only allowed placeholder would be literally `{{userId}}` which would be replaced by your own user id internally, i.e.: `3d843e47-0046-3021-3ac2-e941ce031592`

but you could try to overwrite any file in the storage like this:
```javascript
IO3D.storage.put(file, {
	key: '/ed245e57-7906-4995-8ac2-e742ce107092/170207-1525-1bqjks/floorplan.jpg',
})
```

**Comment by frederic-schwarz** [comment]
that's what I mean
