### ISSUE TITLE
io3d.furniture.search API irregularly returns 400

### ISSUE THREAD

**Issue by tomas-polach** [archilogic-com/3dio-js#27]
todo: write down reproducible bug report

**Comment by AVGP** [comment]
I think this was linked to searching for empty strings which is now working as expected

**Comment by tomas-polach** [comment]
@AVGP any updates on this one? happy to help with testing

**Comment by AVGP** [comment]
Oh, I haven't seen this one in a while, so I'd close it and reopen *if* it comes back...
