### ISSUE TITLE
Move io3d.ui to io3d.utils.ui and io3d.auth to io3d.utils.auth

### ISSUE THREAD

**Issue by tomas-polach** [archilogic-com/3dio-js#29]
i suggest to have only official products being placed in main namespace `io3d` to keep things clean.

moving `io3d.ui` and `io3d.auth` to utils would keep things more consistent with our product definition.

@AVGP @frederic-schwarz what do you think?

**Comment by tomas-polach** [comment]
i will move the methods to `io3d.utils`and keep the old ones as aliases so that we have a grace period to adapt all apps depending on it

**Comment by AVGP** [comment]
agreed to move to utils
