### ISSUE TITLE
Login not working on 3d.io

### ISSUE THREAD

**Issue by tomas-polach** [archilogic-com/3dio-js#30]
repro:
1. goto https://3d.io/dev-dashboard
2. login

result:
you will be asked for password again

expected:
login works

**Comment by tomas-polach** [comment]
might be related to session cookies or https://github.com/archilogic-com/3dio-js/commit/77d2b5064d2a29c0db2299353e767563d1827d2a

**Comment by AVGP** [comment]
Fixed and released in beta.37
