### ISSUE TITLE
normal maps seem to be ignored in io3d-furniture component

### ISSUE THREAD

**Issue by frederic-schwarz** [archilogic-com/3dio-js#34]
compare:

![3d_io_furniture_for_a-frame](https://user-images.githubusercontent.com/7444615/29554042-f663f554-871d-11e7-9c6a-64d7e55fa8a1.png)
https://furniture.3d.io/#furnitureId=ef62bf88-97e9-4468-ad0e-a87ced83578d

![archilogic](https://user-images.githubusercontent.com/7444615/29554066-082e1602-871e-11e7-836e-cc03820e7ecc.png)
https://spaces.archilogic.com/products?productResourceId=ef62bf88-97e9-4468-ad0e-a87ced83578d&view=grid

**Comment by Aadjou** [comment]
Normal map gets loaded in newer models, 
eg. https://furniture.3d.io/#furnitureId=4c49aa5b-9b7b-4d3d-a2d2-60663e712b0e

Must be a problem with getting the right map from texture set, in this case, 'mapNormalPreview' should get loaded instead of 'mapNormal', just a quick guess. I'll look into it.

**Comment by frederic-schwarz** [comment]
ok interesting,
do we actually provide previews for normal maps? because as I remember in the editor on mobile we don't show normal maps

there is quite a few of these 'old' ones
https://furniture.3d.io/#furnitureId=530b8ade-7e13-42a4-89fd-3732941e1750

**Comment by Aadjou** [comment]
you might be right there... let me check a new furniture

**Comment by Aadjou** [comment]
anyway i will look into the texture select mechanism and make it support old models

**Comment by Aadjou** [comment]
Okay I was turning in circles here a bit. The normal map .dds does get loaded (at least it is in the network tab)
(it's hard to find out which dds texture is a normal map, if the texture key has been hached. - this led to confusion)
`furniture.components["io3d-furniture"].data3dView._materials3d['Leather & Shell'].uniforms['normalMap']`
gives us the information that normal map is set in the shader.
Therefore the problem is NOT in the `load-texture.js`

**Comment by tomas-polach** [comment]
i will take care of this.
this is a glitch and not a bug because it does not block key functionality as agreed on bug classification. (lets stick to what we agreed on concerning bug classifications)

**Comment by tomas-polach** [comment]
will work on this today afternoon...

**Comment by tomas-polach** [comment]
fixed :)

`uniforms.normalScale` of type `THREE.Vector2` was missing in data3d parser and in shader uniforms
