### ISSUE TITLE
Add support for material preset in furniture definition

### ISSUE THREAD

**Issue by frederic-schwarz** [archilogic-com/3dio-js#47]
furniture items with alternative Materials can have preset materials in their sceneStructure definition.
support for this allows for more furniture variety within a-frame

**Comment by AVGP** [comment]
if I'm not mistaken, it works when setting the attribute accordingly in
HTML

Am 10.09.2017 5:57 nachm. schrieb "Frederic Schwarz" <
notifications@github.com>:
