### ISSUE TITLE
extend io3d.scene.getAframeElementsFromSceneStructure

### ISSUE THREAD

**Issue by frederic-schwarz** [archilogic-com/3dio-js#49]
- [x] plan & level elements
- [x] nested elements
- [x] id -> io3d-uuid attribute
- [x] camera tour
- [x] type: object (custom 3d models )
- [x] getting baked model -> io3d-data3d, read status file to fetch hi-res bake even if not saved in sceneStructure

**Comment by AVGP** [comment]
280c283731995ad8aaf51b5d579d1a3a9344f7a1 ships `object` and baked model support (including polling)

**Comment by frederic-schwarz** [comment]
todos:
* Waypoints are twice in the output. (tour waypoint in camera element AND a-entity with uuid in level) waypoints should only be in camera element with uuid
* make waypoint uuid the selector - not the name ( avoid duplicate name clash )
* io3d-data3d is now part of the level entitiy - this can result in conflicts with for instance shadow property
cleaner would be to make the bakedModel object a child of the level entitiy

**Comment by AVGP** [comment]
So those bits are done, time for more testing 😎

**Comment by frederic-schwarz** [comment]
great will do

**Comment by frederic-schwarz** [comment]
as of now two remaining issues regarding scene api:
- [ ] get initial camera position https://github.com/archilogic-com/3dio-js/blob/scene-api/src/scene/structure/to-aframe-elements.js#L149
- [ ] still camera-bookmark issues
check out this apartment: 62cb3510-6708-4f62-94c3-f9936db7e20b
compare: dining or bedroom waypoints in here: https://spaces.archilogic.com/3d/archilogic/h4959x0g?modelResourceId=62cb3510-6708-4f62-94c3-f9936db7e20b&mode=edit&view-menu=camera-bookmarks&main-menu=json
and using `/examples-browser/scene/index.html`

**Comment by frederic-schwarz** [comment]
different module but still blocking: https://github.com/archilogic-com/3dio-js/issues/66

**Comment by frederic-schwarz** [comment]
cam pos fixed here: https://github.com/archilogic-com/3dio-js/commit/527b35df35137bef45e5204353d6e99293e583e7
