### ISSUE TITLE
Can't login / upload files to specific directory from node server

### ISSUE THREAD

**Issue by bnjm** [archilogic-com/3dio-js#54]
In the docs there is the example for uploading files to a specific directory 

```var file = new Blob(['Hello World'])

// uploading a file to specific location requires login
io3d.utils.auth.login({
  username: 'your-username-here',
  password: 'your-password-here'
}).then(function (session) {
  return io3d.storage.put(file, {
    key: '/' + session.user.id + '/my-folder-name/my-file-name.txt'
  })
}).then(function (key) {
  console.log('Done')
})
```
This seems currently not possible from node environments because `io3d.utils.auth.login` won't receive a receive a session cookie ... catching at this promise:
https://github.com/archilogic-com/3dio-js/blob/034bd01442fd74614bb05e8689e7431e6fd336ef/src/utils/auth/log-in.js#L44

If I'm not messing something up and problem *is* due to the environment, it would be great to allow either

- an alternate way to login from node environments (i.e. firebase) 
- an alternate way to allow for specific directory file uploads (maybe using secret-api-key)
- a more specific error message saying that this is only supported in the browser (or maybe with session-cookie middleware)

**Comment by tomas-polach** [comment]
use secretApiKey ;) agree: we can improve the current situation a lot by giving meaningful error messages

**Comment by bnjm** [comment]
Thanks for the error message to suggest using secretApiKey. 

I tried that with the following code which still returns `Unhandled rejection You have to be logged in to store files in a specific location`:

```
const io3d = require('3dio')
const file = new Buffer(['Hello World'])

// uploading a file to specific location requires login
io3d.config({
  secretApiKey: '...'
})

io3d.storage
  .put(file, {
    key: '/my-folder-name/my-file-name.txt'
  })
  .then(console.log)
```

**Comment by tomas-polach** [comment]
thx for testing!! can you pls create a separate issue for that?

**Comment by bnjm** [comment]
sure :D
