### ISSUE TITLE
add jshint to release script

### ISSUE THREAD

**Issue by tomas-polach** [archilogic-com/3dio-js#64]
in order to prevent some common bugs like from variable definitions inside `if`,  ES6 being used accidentaly etc. we should add jshint to the release script.

we do not want to overdo it for now (we will get more strict later). therefore i suggest to check only for critical stuff:

(see https://github.com/jshint/jshint/blob/master/src/messages.js for options reference)
```javascript
var jsHintOptions = {
     esversion: 5,
     undef: true,
     unused: false,
     asi: true,
     eqeqeq: false,
     '-W041': false,
     '-W002': false,
     '-W080': false,
     '-W032': false,
     '-W030': false,
     '-W046': false,
     '-W008': false,
     '-W083': false,
     '-W084': false,
     '-W054': false,
     '-W009': false,
     '-W010': false,
     '-W047': false,
     '-W018': false,
     '-W027': false,
     '-W055': false,
     '-W086': false,
     laxcomma  : true,
     laxbreak  : true,
     sub:true,
     shadow:true,
     browser: true,
     node: true,
     devel: true,
     validthis: true
}
```

**Comment by tomas-polach** [comment]
i guess gulp-jshint is the way to go? https://www.npmjs.com/package/gulp-jshint

**Comment by AVGP** [comment]
go ahead :)

2017-09-28 14:58 GMT+00:00 Tomas Polach <notifications@github.com>:

**Comment by AVGP** [comment]
did I see this right - it's landed right?

**Comment by tomas-polach** [comment]
yep, landed! i just forgot to close this issue...
