### ISSUE TITLE
Io3d.utils.io.checkIfFileExists resolves with true even if url 

### ISSUE THREAD

**Issue by Aadjou** [archilogic-com/3dio-js#65]
How to reproduce:
run `io3d.utils.io.checkIfFileExists("randomstring").catch(console.error("url not found")).then(console.log)`
in the console

Result:
![checkiffileexists](https://user-images.githubusercontent.com/25610447/30488535-8672bcae-9a36-11e7-972f-e6a17a9d544c.PNG)
- Returns true even if file does not exist
- We can catch the error from fetch -> properly suggests that url was not found

Expected result:
- no error catched
- return false if file does not exist

**Comment by tomas-polach** [comment]
always use catch at the end of a promise chain. in this case:
```javascript
io3d.utils.io.checkIfFileExists("randomstring")
  .then(console.log)
  .catch(console.error)
```

**Comment by tomas-polach** [comment]
hope this helps? :)

**Comment by Aadjou** [comment]
but you agree that the function should return false in this case, right?

**Comment by tomas-polach** [comment]
yes.
```javascript
io3d.utils.io.checkIfFileExists("randomstring")
  .then(console.log)
  .catch(console.error)
```
- if file exists: // true
- file does not exist: // false

**Comment by tomas-polach** [comment]
sorry, you are right: bullshit URL returns `true` even if catch is at the end:/

**Comment by Aadjou** [comment]
thanks, i was not sure if it was intentional.

**Comment by tomas-polach** [comment]
fixed, gave it some testing and the method seems to behave correctly now. @Aadjou can you confirm pls?

<img width="595" alt="3d_io" src="https://user-images.githubusercontent.com/6619499/30492245-80593e44-9a48-11e7-85ae-acd5907b2bc7.png">

**Comment by AVGP** [comment]
Ah I see I'm not the only one who gets surprised by the design of fetch.

Fetch resolves the promise if it **gets a response**.

That response can be 5xx or 4xx,though.

Fetch is designed to be a low level primitive that leaves handling of
responses, including error responses, to the user.

This means that the promise resolves and the response needs to be inspected
before returning it to higher layers.

That can be very convenient, for instance in our jsonrpc client in the
dashboard I can still access `response.json()` to deal with errors and then
reject from there.

**Comment by tomas-polach** [comment]
true that. fetch gives you lot of controls but that comes with more responsibility.

i.e. have a look at the error handler in io3d.utils.services.call()
https://github.com/archilogic-com/3dio-js/blob/master/src/utils/services/call.js#L87

**Comment by AVGP** [comment]
The JSONRPC client in the dashboard has an additional step:

https://github.com/archilogic-com/services/blob/c0a0d3fba880bd328abba33e9d4d11370269f8c7/client/src/admin/js/jsonrpc.js#L58

**Comment by tomas-polach** [comment]
nice! code is much more readable in the dashboard version! (i will adapt io3d accordingly)

there is one edge case where io3d error handler is more helpful though: when JSON parsing fails it error-logs the body as text. this helped me with debugging once...

**Comment by AVGP** [comment]
True that, which means both parts of the code just get better now 🎉
