### ISSUE TITLE
Camera jumps to random position (tour component?)

### ISSUE THREAD

**Issue by david-tran-archilogic** [archilogic-com/3dio-js#66]
**How to:**
- open: https://quickest-cone.glitch.me/
- click on the "Overview" bookmark (Perspective, Bedroom and Bedroom2 work too)
- wait till the camera stops moving
- left click into the scene
- press w, a, s, d, left-, right-, up- or down- key on your keyboard

**Expected behavior:**
Camera moves into the direction of the key

**Actual result:**
Camera jumps to a "random" position.

Suspicion: maybe it has something to do with the camera rotation and the tour component?

**Comment by AVGP** [comment]
In debugging this I noticed:

* It's definitely the tour component. Without it, the behaviour doesn't occur
* It's something with property values, 'cause `setAttribute` of position and rotation seems to fix the problem

So I'll have a look at the component again to see what's up with that

**Comment by frederic-schwarz** [comment]
I had the feeling this only occurs with camera y position being non-standard.
and when it happens it looks like camera position values are multiplied by factor 10

**Comment by AVGP** [comment]
There seems to be a correlation with that as well, but no code in the component warrants that to be a special case. What I can tell right now is: Flushing the position out to the DOM explicitely fixes the issue - but I still don't know for sure why that is.
