### ISSUE TITLE
Design io3d.convert API

### ISSUE THREAD

**Issue by bnjm** [archilogic-com/3dio-js#70]
End goal: Allow users to export data3d to other 3d formats (such as gltf, obj, dae)

Proposal: Ability to do something like 
```
io3d.furniture.getData3dStorageId( furnitureId )
	.then(io3d.export.dae)
	.then(io3d.export.whenDone)
	.then(io3d.storage.getUrlFromStorageId){
	.then(function(url)){
		console.log('your export is ready: '+url)
	})
```

Considerations: `export` keyword is reserved in javascript...what happens if people do 

`import { export } from io3d`

**Comment by bnjm** [comment]
I don't think the method should be called `export` because it complicates things for people wanting to import modules: 

![screen shot 2017-09-25 at 19 35 46](https://user-images.githubusercontent.com/1694288/30822382-d3d92c7c-a228-11e7-8f28-0b62d71d7a37.png)

**Comment by Aadjou** [comment]
it's called convert

**Comment by bnjm** [comment]
Makes things easier :D I updated the issue title

**Comment by bnjm** [comment]
https://github.com/archilogic-com/3dio-js/pull/75
