### ISSUE TITLE
image upload and retrive ?

### ISSUE THREAD

**Issue by vaibhavlinux** [archilogic-com/3dio-js#80]
i upload image using this folder path (https://github.com/archilogic-com/3dio-js/tree/master/examples-browser/storage-app) image uploaded is successfully in this path ( https://s3-eu-west-1.amazonaws.com/archilogic-content-beta/temp%2F2017-10-03_10-14-25_Suux0I%2FKoala.jpg )
but how can i get this image in  furniture library

**Comment by AVGP** [comment]
Hey @vaibhavlinux - thank you for opening an issue.

First things first: Let's clarify a few things.

* Upload API: The upload API is meant for uploading files, such as images or 3D models.
* Furniture library: The furniture library is provided by Archilogic and, right now, does not have a feature to allow adding furniture to it. If that's what you want to do, let me know and I'll see what we can do.

If you have a 3D model, say in [glTF](https://www.khronos.org/gltf) or [OBJ](https://spaces.archilogic.com/blog/what-is-an-obj-file) format, you can upload it with the upload API and then use it in A-Frame.

Say you uploaded your glTF file to `https://storage.3d.io/temp/2017-10-03_10-14-25_abc123/model.gltf`, then you can use it in A-Frame like this:

```html
<a-scene>
  <a-entity gltf-model="url(https://storage.3d.io/temp/2017-10-03_10-14-25_abc123/model.gltf)"></a-entity>
</a-scene>
```

Would you be so kind and tell me what the goal is you're trying to accomplish so I can make sure to help you?

Thanks & cheers,
Martin

**Comment by vaibhavlinux** [comment]
hello sir

i want to show furniture same as this url demos  (
https://twitter.com/ow/status/910400072738885638)

and this is my working url (
https://elancethemes.com/25/arm/aframe/examples/demo-3dio/basic.html ) plz
open it in mobile

I am using this code

<script src="https://aframe.io/releases/0.6.1/aframe.min.js"></script>
<script src="https://jeromeetienne.github.io/AR.js/aframe/build/aframe-ar.js
"></script>
<script src="
https://cdn.rawgit.com/tizzle/aframe-orbit-controls-component/v0.1.12/dist/aframe-orbit-controls-component.min.js
"></script>
<script src="https://3d.io/releases/3dio-js/1.x.x-beta/3dio.min.js
"></script>
<body>
<a-scene antialias="true">
  <a-entity id="furniture"
io3d-furniture="id:fb4d9b0d-28e9-4669-be11-6da7316a040a"  shadow='receive:
true' scale='0.5 0.5 0.5' rotation='-90 0 0'"  position='0 0 0 '></a-entity>
  <a-entity camera position="0 3.6 0"
orbit-controls="target:#furniture;"></a-entity>
</a-scene>
</body>


I dont know how can i upload gtlf file to https://storage.3d.io/temp/
2017-10-03_10-14-25_abc123/model.gltf,

plz help me sir

thanks
vaibhav bargal

**Comment by frederic-schwarz** [comment]
you can use the Archilogic editor for that
https://docs.archilogic.com/en/3d-editor/custom-3d-data/import.html
drag and drop obj including textures into the editor window and copy the storage id into your a-frame io3d-data3d component

https://spaces.archilogic.com/3d/template/empty

![archilogic](https://user-images.githubusercontent.com/7444615/31183158-10460ed8-a926-11e7-8853-81813d9143f7.png)
```html
<a-entity io3d-data3d="key:/97fa0bf7-1405-4fe3-a2be-49d2101d4121/171004-1659-lmclg1/d2d3f5c9-8e41-4c63-9c8a-4a7899146456.gz.data3d.buffer" position="0 0 -5">
```
