### ISSUE TITLE
Order.complete.basic.success API does not include models ordered with API Key

### ISSUE THREAD

**Issue by sjeftijssen** [archilogic-com/3dio-js#83]
Actual:
Basic models ordered with an API Key with author Web S are correctly triggering the FloorPlan.convertToBasic3dModel API however when model is closed it is not triggering the order.complete.basic.success (fail)

Expect:
Expect any completed instances of basic models ordered with an API key and Web S author to be counted in order.complete.basic.success. (fail)

**Comment by m-ke** [comment]
doesn't belong in this repository
