### ISSUE TITLE
Aframe Components: Add Lightmap Saturation to Shader Material

### ISSUE THREAD

**Issue by Aadjou** [archilogic-com/3dio-js#85]
We want to have full control over the look of the lightmaps.

So in order to remove the desaturation workaround in the backend, 
we want to add an additional control function to control the saturation of the lightmaps to the lightmap parameters (exposure & intensity)

Quick draft:

Parameter | Description
-- | --
lightMapIntensity | Intensity (default 1.2) of the lightmap being applied
lightMapExposure | Exposure (default 0.6) of the lightmap being applied
**lightMapSaturation** | Saturation of the lightmap, 0 -> grayscale image, 1 -> full color

- Values above 1, should oversaturation be possible?

**Comment by Aadjou** [comment]
Nice read:
https://stackoverflow.com/questions/9234724/how-to-change-hue-of-a-texture-with-glsl

**Comment by tomas-polach** [comment]
nice! i might be mistaking but hue and saturation are two different things, no?

**Comment by Aadjou** [comment]
you are not mistaken but it's just a clue on how to get started with image pixel manipulation

**Comment by Aadjou** [comment]
grayscale texture:
void main()
```
{
         // Convert to grayscale using NTSC conversion weights
    float gray = dot(gl_Color.rgb, vec3(0.299, 0.587, 0.114));
    
    gl_FragColor = vec4(gray, gray, gray, gl_Color.a);
}
```

**Comment by Aadjou** [comment]
Ready for testing
